title:       "Operating Systems 2021-2 (OS212)"
version:     "1"
copyright:   "2021-2021"
description: >- 
  OS class is fun ngl
google_analytics: "UA-89852122-13"
author:           "ReeyaDono"
address:          "Empty"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://reeyadono.github.io/os212/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/ReeyaDono/os212"
urlghpage:        "https://reeyadono.github.io/os212/"
keywords:         "jekyll, testing"
github:           
  - metadata

